# Generated by Django 6.0 on 2026-03-25 11:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_recipe_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_upload',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image_upload'),
        ),
    ]
